# Generated by Django 5.0.4 on 2024-05-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-time_in',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup',
        ),
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Заказ выполнен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='take_away',
            field=models.BooleanField(default=False, verbose_name='Доставка по адресу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Заказ оформлен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_out',
            field=models.DateTimeField(null=True, verbose_name='Заказ выдан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
    ]
